### ISSUE TITLE
will this work with win 10?

### ISSUE THREAD

**Issue by GANESH312006** [Zingzy/hPyT#10]

**Comment by Zingzy** [comment]
Yes, most of the functions must work with windows 10 although it is not tested.

**Features that are known to not work**:

- Custom Titlebar color
- Custom TitleBar Text Color
- Rainbow Titlebar

You can install the [hPyT Preview app](https://github.com/Zingzy/hPyT/releases/tag/hPyT-preview/) and run it on widows 10 to check other functions too.

**Comment by vihaanmody1** [comment]
It does work on Win 10. I have it working. Great Library

**Comment by Zingzy** [comment]
Thanks good to know!

**Comment by GANESH312006** [comment]
> It does work on Win 10. I have it working. Great Library

nah man, it doesnt. I tried with win 10

**Comment by Zingzy** [comment]
> > It does work on Win 10. I have it working. Great Library
> 
> nah man, it doesnt. I tried with win 10

Well some of the functions are not supposed to work on windows 10 because this package uses windows API.

**Comment by GANESH312006** [comment]
> > > It does work on Win 10. I have it working. Great Library
> > 
> > 
> > nah man, it doesnt. I tried with win 10
> 
> Well some of the functions are not supposed to work on windows 10 because this package uses windows API.

yea man, changing title bar color is not working with win 10

**Comment by Zingzy** [comment]
> > > > It does work on Win 10. I have it working. Great Library
> > > 
> > > 
> > > nah man, it doesnt. I tried with win 10
> > 
> > 
> > Well some of the functions are not supposed to work on windows 10 because this package uses windows API.
> 
> yea man, changing title bar color is not working with win 10

There is no workaround for that sadly unless you create a custom titlebar 🙂

**Comment by GANESH312006** [comment]
> > > > > It does work on Win 10. I have it working. Great Library
> > > > 
> > > > 
> > > > nah man, it doesnt. I tried with win 10
> > > 
> > > 
> > > Well some of the functions are not supposed to work on windows 10 because this package uses windows API.
> > 
> > 
> > yea man, changing title bar color is not working with win 10
> 
> There is no workaround for that sadly unless you create a custom titlebar 🙂

yea fr, we cant do anything with that lmao
