### ISSUE TITLE
Can't use hPyT with root.resizable

### ISSUE THREAD

**Issue by TerseSmile10428** [Zingzy/hPyT#16]
Maybe I didn't look good at the read me text or anything like that but I want to use the resizable feature in tkinter and it just doesn't let me because of hPyT, any way to fix that?

**Comment by Zingzy** [comment]
Hey @TerseSmile10428 can you please show me the code which you used?

**Comment by TerseSmile10428** [comment]
Sure, I'm using 2 codes so if you run the code it wont work.
# Imports
from tkinter import *

import hPyT

from Configuration import *
from PIL import Image, ImageTk
from hPyT import *


# Function to handle the focus in event for the youtubeLink_entry
def on_focus_in_youtubeLink_entry(event):
    if youtubeLink_entry.get() == 'Paste link':
        youtubeLink_entry.delete(0, 'end')  # delete all the text in the entry
        youtubeLink_entry.config(fg='black')


# Function to handle the focus out event for the youtubeLink_entry
def on_focus_out_youtubeLink_entry(event=None):
    if youtubeLink_entry.get() == '':
        youtubeLink_entry.insert(0, 'Paste link')
        youtubeLink_entry.config(fg='grey')


# Function to handle the focus in event for the locationLink_entry
def on_focus_in_locationLink_entry(event):
    if locationLink_entry.get() == 'Paste here':
        locationLink_entry.delete(0, 'end')  # delete all the text in the entry
        locationLink_entry.config(fg='black')


# Function to handle the focus out event for the locationLink_entry
def on_focus_out_locationLink_entry(event=None):
    if locationLink_entry.get() == '':
        locationLink_entry.insert(0, 'Paste here')
        locationLink_entry.config(fg='grey')


def toggle_radio(button):
    if button == 1:
        MP3_radioButton.config(image=checked_photo)
        MP4_radioButton.config(image=unchecked_photo)
    elif button == 2:
        MP3_radioButton.config(image=unchecked_photo)
        MP4_radioButton.config(image=checked_photo)


def focus_out_all_entries(event):
    widget = event.widget
    if widget not in (youtubeLink_entry, locationLink_entry):
        root.focus()  # Set focus to root, effectively removing focus from entry fields
        on_focus_out_youtubeLink_entry()
        on_focus_out_locationLink_entry()


root = Tk()
root.title("‎")
root.iconbitmap("Assets/Images/Icons/TitleIcon/TitleIcon.ico")
root.geometry('374x638')
root.configure(background="white")

# Load and resize images
checked_image = Image.open('Assets/Images/Widgets/Radio/active.png')
unchecked_image = Image.open('Assets/Images/Widgets/Radio/Inactive.png')
checked_photo = ImageTk.PhotoImage(checked_image)
unchecked_photo = ImageTk.PhotoImage(unchecked_image)

var = IntVar()

frame_1_for_title = Frame(root, width=390, height=72, bg=Background_Color)
frame_1_for_title.place(x=0, y=0)

frame_2_for_title = Frame(frame_1_for_title, width=358, height=48, bg=Background_Color)
frame_2_for_title.place(x=8, y=16)

frame_3_for_title = Frame(frame_2_for_title, width=262, height=22, bg=Background_Color)
frame_3_for_title.place(x=48, y=12)

frame_4_for_title = Frame(frame_3_for_title, width=204, height=22, bg=Background_Color)
frame_4_for_title.place(x=29, y=0)

title = Label(frame_4_for_title, text="Youtube to video", fg="white", bg=Background_Color, font=('Helvetica', 16))
title.place(x=15, y=0)

# Link entry and label.
frame_1_for_link_entry_and_label = Frame(root, width=374, height=112, bg=Background_Color)
frame_1_for_link_entry_and_label.place(x=0, y=72)

frame_2_for_link_entry_and_label = Frame(frame_1_for_link_entry_and_label, width=358, height=88, bg=Background_Color)
frame_2_for_link_entry_and_label.place(x=8, y=12)

label_frame = Frame(frame_2_for_link_entry_and_label, width=358, height=32, bg=Background_Color)
label_frame.place(x=0, y=0)

youtubeLink_label = Label(label_frame, text="Youtube link", bg=Background_Color, fg="white", font=16)
youtubeLink_label.place(x=0, y=0)

# Image and entry field
entry_name = PhotoImage(file='Assets/Images/Widgets/Youtube_link/EntryWidget.png')
entry_image = Label(frame_2_for_link_entry_and_label, image=entry_name, border=0, bg=Background_Color)
entry_image.place(x=0, y=32)

frame_for_paste_button = Frame(entry_image, width=24, height=24, bg='pink')
frame_for_paste_button.place(x=318, y=16)

youtubeLink_entry = Entry(entry_image, border=0, bg='white', font=('bold', 16))
youtubeLink_entry.insert(0, 'Paste link')
youtubeLink_entry.bind('<FocusIn>', on_focus_in_youtubeLink_entry)
youtubeLink_entry.bind('<FocusOut>', on_focus_out_youtubeLink_entry)
youtubeLink_entry.place(x=20, y=5, height=50, width=300)  # Adjusted y-coordinate to avoid overlap with the image

Paste_button_Icon = PhotoImage(file='Assets/Images/Icons/EntryButtons/PasteButton.png')
Paste_button = Button(frame_for_paste_button, border=0, bg='white', image=Paste_button_Icon)
Paste_button.place(x=0, y=0)

frame_for_format_label = Frame(root, width=54, height=45, bg=Background_Color)
frame_for_format_label.place(x=8, y=201)

format_label = Label(frame_for_format_label, text="Format", font=16, fg="white", bg=Background_Color)
format_label.place(x=0, y=0)

radio_buttons_frame = Frame(root, width=256, height=151, bg=Background_Color)
radio_buttons_frame.place(x=61, y=200)

Widget_for_radio_button_MP3_or_MP4_Icon = PhotoImage(file='Assets/Images/Widgets/Radio/RadioWidget.png')

Widget_for_radio_button_MP3 = Label(radio_buttons_frame, image=Widget_for_radio_button_MP3_or_MP4_Icon, bg='blue')
Widget_for_radio_button_MP3.place(x=20, y=20)

# Create labels to act as radio buttons
MP3_radioButton = Label(Widget_for_radio_button_MP3, image=checked_photo, border=0)
MP3_radioButton.place(x=12, y=11)
MP3_radioButton.bind("<Button-1>", lambda e: toggle_radio(1))

MP3_text = Label(Widget_for_radio_button_MP3, text="Sound", fg=text_Color, bg=widget_Color, font=12)
MP3_text.place(x=54, y=17)

Widget_for_radio_button_MP4 = Label(radio_buttons_frame, image=Widget_for_radio_button_MP3_or_MP4_Icon, bg='blue')
Widget_for_radio_button_MP4.place(x=20, y=82)

MP4_radioButton = Label(Widget_for_radio_button_MP4, image=unchecked_photo, border=0)
MP4_radioButton.place(x=12, y=11)
MP4_radioButton.bind("<Button-1>", lambda e: toggle_radio(2))

MP4_text = Label(Widget_for_radio_button_MP4, text="Video", fg=text_Color, bg=widget_Color, font=12)
MP4_text.place(x=54, y=17)

frame_1_for_location_entry_and_label = Frame(root, width=390, height=112, bg='black')
frame_1_for_location_entry_and_label.place(x=0, y=339)

frame_2_for_location_entry_and_label = Frame(frame_1_for_location_entry_and_label, width=358, height=88, bg='blue')
frame_2_for_location_entry_and_label.place(x=8, y=12)

frame_for_label_location = Frame(frame_2_for_location_entry_and_label, width=358, height=32, bg='green')
frame_for_label_location.place(x=0, y=0)

location_label = Label(frame_for_label_location, text="Location", fg=text_Color, bg=widget_Color, font=16)
location_label.place(x=0, y=0)

location_entry_widget = PhotoImage(file='Assets/Images/Widgets/Location/EntryWidget.png')
location_entry = Label(frame_2_for_location_entry_and_label, image=entry_name, border=0, bg='black')
location_entry.place(x=0, y=32)

locationLink_entry = Entry(location_entry, border=0, bg='white', font=('bold', 16))
locationLink_entry.insert(0, 'Paste here')
locationLink_entry.bind('<FocusIn>', on_focus_in_locationLink_entry)
locationLink_entry.bind('<FocusOut>', on_focus_out_locationLink_entry)
locationLink_entry.place(x=20, y=5, height=50, width=300)

# Bind a click event to the root to unfocused the entries when clicking anywhere else
root.bind_all('<Button-1>', focus_out_all_entries, add="+")

browse_button_image = PhotoImage(file="Assets/Images/Widgets/Other/BrowseWidget.png")
browse_button = Label(root, image=browse_button_image, bg="black")
browse_button.place(x=115, y=463)

title_bar_color.set(root, Background_Color)


root.mainloop()

**Comment by Zingzy** [comment]
I tried running this code and it worked fine for me:

```py
from tkinter import *
from hPyT import *
root = Tk()
root.resizable(False, False)
rainbow_title_bar.start(root)
```

https://github.com/Zingzy/hPyT/assets/90309290/5d04ceec-cc2b-44e4-b50a-71a03bf03fed

**Comment by TerseSmile10428** [comment]
i will check, thanks

**Comment by Zingzy** [comment]
hi @TerseSmile10428 can you please confirm whether your problem was solved?

**Comment by TerseSmile10428** [comment]
It was solved, thanks
