### ISSUE TITLE
Add the ability to disable or enable the close button

### ISSUE THREAD

**Issue by Xiaokang2022** [Zingzy/hPyT#19]
Is it possible to add the ability to disable or enable the close button?

**Comment by Zingzy** [comment]
Hello @Xiaokang2022 unfortunately I could not find any way to just disable the close button, right now you could just disable the minimize, maximize buttons independently.

**Comment by Xiaokang2022** [comment]
@Zingzy Is it possible to add this feature in the future?

**Comment by Zingzy** [comment]
@Xiaokang2022 To be honest, I am not sure. This library is a wrapper for the official Windows DWM API. I try to integrate as many features as possible, but I am limited by the DWM API.

**Comment by Xiaokang2022** [comment]
Well, while it's a shame not to have this feature, there are still plenty of other interesting features to use for this project! Thank you for getting back to me!
