### ISSUE TITLE
Not support Linux？

### ISSUE THREAD

**Issue by c61292558** [Zingzy/hPyT#25]
Not support Linux？
It seems can't run on Linux.

**Comment by Zingzy** [comment]
hPyT is only meant to work on windows as it uses the official Windows DWM API to modify the GUIs.. If there I find a way to do that in Linux and if there is a demand for it, I would add custom functions for Linux too

**Comment by c61292558** [comment]
> hPyT is only meant to work on windows as it uses the official Windows DWM API to modify the GUIs.. If there I find a way to do that in Linux and if there is a demand for it, I would add custom functions for Linux too

Thank you very much, I will wait for your Linux version.
